# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: Manual Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request_target:
    types: [assigned, opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-transition-issue:
    name: Convert Github Issue to Jira Issue
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@develop
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
    - name: Get network info
      run: ifconfig
          
