# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Check Pull Request
on: 
  pull_request:
      types: [opened, edited, review_requested, synchronize, review_request_removed, reopened]
      branches:
  workflow_dispatch:
env:
  SECURITY: APP_SECURE=false
  COMMAND: all
  COMPONENT: all
jobs:
  
  document-generation:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.69
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Remove Libraries
      run: rm -rf EFR32_ICE60730_Libraries
    - name: Create directory for Libraries
      run: mkdir EFR32_ICE60730_Libraries
    - name: Generate Documents with Doxygen
      run: doxygen qat.doxygen
    - name: Upload Documents
      uses: actions/upload-artifact@v4.3.4
      with:
        path: 
          Doc/html/EFR32_ICE60730_Libraries/
        warn: Output a warning but do not fail the action
        retention-days: 90

  gcc-mg12-regression-test:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.69
      SERIAL_NUM: 440111030
      COMPILER: GCC
      PLATFORM: MG12
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Check working directory
      run: 
        pwd
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test
        cd Test
    - name: Assign environment variables
      run: 
        export TOOL_DIRS=/home/sqa/SimplicityStudio-5/SimplicityStudio_v5/developer/toolchains/gnu_arm/10.3_2021.10/bin
        whoami
        export HOST_IP=$HOST_IP
        export COMPILER=GCC
        export APP_TYPE=SecureApp
        
    - name: Testing
      run: ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run: 
        python test_script/get_report.py
        cd ../
    - name: Upload results and logs
      uses: actions/upload-artifact@v4.3.4
      with:
        path: 
          result/
          artifact/
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90
  
  gcc-mg24-regression-test:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.100
      SERIAL_NUM: 440124068
      COMPILER: GCC
      PLATFORM: MG24
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Check working directory
      run: 
        pwd
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test
        cd Test
    - name: Assign environment variables
      run: 
        export TOOL_DIRS=/home/sqa/SimplicityStudio-5/SimplicityStudio_v5/developer/toolchains/gnu_arm/10.3_2021.10/bin
        whoami
        export HOST_IP=$HOST_IP
        export COMPILER=GCC
        export APP_TYPE=SecureApp

    - name: Testing
      run: ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run: 
        python test_script/get_report.py
        cd ../
    - name: Upload results and logs
      uses: actions/upload-artifact@v4.3.4
      with:
        path: 
          result/
          artifact/
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90
  
  iar-mg12-regression-test:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.69
      SERIAL_NUM: 440111030
      COMPILER: IAR
      PLATFORM: MG12
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Check working directory
      run: 
        pwd
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test
        cd Test
    - name: Assign environment variables
      run: 
        whoami
        export HOST_IP=$HOST_IP
        export TOOL_DIRS=/home/sqa/EmbeddedWorkbench8.4/arm/bin
        export APP_TYPE=SecureApp

    - name: Testing
      run: ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run: 
        python test_script/get_report.py
        cd ../
    - name: Upload results and logs
      uses: actions/upload-artifact@v4.3.4
      with:
        path: 
          result/
          artifact/
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90
  
  iar-mg24-regression-test:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.100
      SERIAL_NUM: 440124068
      COMPILER: IAR
      PLATFORM: MG24
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Check working directory
      run: 
        pwd
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test
        cd Test
    - name: Assign environment variables
      run: 
        whoami
        export HOST_IP=$HOST_IP
        export TOOL_DIRS=/home/sqa/EmbeddedWorkbench8.4/arm/bin
        export APP_TYPE=SecureApp

    - name: Testing
      run: ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run: 
        python test_script/get_report.py
        cd ../
    - name: Upload results and logs
      uses: actions/upload-artifact@v4.3.4
      with:
        path: 
          result/
          artifact/
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90

  result-summary:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
  
  
          
